// <auto-generated />
using System;
using ArtGallery.CJ.WEB.Infrastructure.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArtGallery.CJ.WEB.Migrations
{
    [DbContext(typeof(ArtDBContext))]
    partial class ArtDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ArtGallery.CJ.WEB.Infrastructure.Domain.Model.Artist", b =>
                {
                    b.Property<Guid?>("ArtistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Age")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("StyleOfWork")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ArtistID");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistID = new Guid("c8bd6bfd-43df-4d36-930b-463bc154b19f"),
                            Age = "91",
                            BirthPlace = "France",
                            Name = "Paul Cezanne",
                            StyleOfWork = "Drawing, Painting"
                        },
                        new
                        {
                            ArtistID = new Guid("c8bd6bfd-43df-4d36-930b-463bc154b20f"),
                            Age = "94",
                            BirthPlace = "Italy",
                            Name = "Caravaggio",
                            StyleOfWork = "Drawing, Painting, Biography"
                        },
                        new
                        {
                            ArtistID = new Guid("c8bd6bfd-43df-4d36-930b-463bc154b11f"),
                            Age = "52",
                            BirthPlace = "Italy",
                            Name = "Leonardo Da Vinci",
                            StyleOfWork = "Renaissance man, Universal Genius, Unquenchable curiosity, Feverishly Inventive Imagination"
                        },
                        new
                        {
                            ArtistID = new Guid("c8bd6bfd-43df-4d36-930b-463bc154b18f"),
                            Age = "97",
                            BirthPlace = "France",
                            Name = "Marcel Duchamp",
                            StyleOfWork = "Painting, Sculpture, Writer, Ches Player"
                        },
                        new
                        {
                            ArtistID = new Guid("c8bd6bfd-43df-4d36-930b-463bc154b12f"),
                            Age = "85",
                            BirthPlace = "Spain",
                            Name = "Pablo Picasso",
                            StyleOfWork = "Drawing, Painting, Cerematic, Sculpture, Printmaking, Writing, Stage Design"
                        });
                });

            modelBuilder.Entity("ArtGallery.CJ.WEB.Infrastructure.Domain.Model.Artwork", b =>
                {
                    b.Property<Guid?>("ArtworkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ArtistID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Medium")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Year")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ArtworkID");

                    b.ToTable("Artworks");

                    b.HasData(
                        new
                        {
                            ArtworkID = new Guid("532ea9f5-d95d-4902-be71-57b7ba7350b5"),
                            ArtistID = new Guid("c8bd6bfd-43df-4d36-930b-463bc154b18f"),
                            Content = "sad young man who is in a corridor and who is moving about; thus there are two parallel movements corresponding to each other",
                            Medium = "Oil on canvas",
                            Title = "Nude Descending a Staircase, No. 2 ",
                            Year = "1912"
                        },
                        new
                        {
                            ArtworkID = new Guid("e055bbda-6c14-44db-a63d-f2c2c658ad44"),
                            ArtistID = new Guid("c8bd6bfd-43df-4d36-930b-463bc154b19f"),
                            Content = "treat nature in terms of the cylinder, the sphere and the cone",
                            Medium = "Oil-on-canvas",
                            Title = "The Bathers",
                            Year = "1898–1905"
                        },
                        new
                        {
                            ArtworkID = new Guid("e3ba8ee4-24e1-4741-a477-fb6b9e850bb3"),
                            ArtistID = new Guid("c8bd6bfd-43df-4d36-930b-463bc154b20f"),
                            Content = "painted for the Cardinal youths playing music very well drawn from nature and also a youth playing a lute",
                            Medium = "Oil on canvas",
                            Title = "The Musicians",
                            Year = "1595"
                        },
                        new
                        {
                            ArtworkID = new Guid("1b5ca85a-eb8f-436b-a6d1-641ee8a13702"),
                            ArtistID = new Guid("c8bd6bfd-43df-4d36-930b-463bc154b14f"),
                            Content = "It was intended as disparagement but the Impressionists appropriated the term for themselves",
                            Medium = "Oil on canvas",
                            Title = "Impression, Sunrise",
                            Year = "1872"
                        },
                        new
                        {
                            ArtworkID = new Guid("b86b50ce-9bc7-4470-a4f2-50a4bd878ace"),
                            ArtistID = new Guid("c8bd6bfd-43df-4d36-930b-463bc154b15f"),
                            Content = " two people who had been identified as Rembrandt himself and his wife Saskia",
                            Medium = "Oil on Canvas",
                            Title = "The Prodigal Son in the Brothel",
                            Year = "1637"
                        },
                        new
                        {
                            ArtworkID = new Guid("f0946a77-1f0d-47a6-afc4-f7f3bf9e6544"),
                            ArtistID = new Guid("c8bd6bfd-43df-4d36-930b-463bc154b12f"),
                            Content = "The Man with the Blue Guitar",
                            Medium = " oil painting ",
                            Title = "The Old Guitarist",
                            Year = "1903"
                        });
                });

            modelBuilder.Entity("ArtGallery.CJ.WEB.Infrastructure.Domain.Model.User", b =>
                {
                    b.Property<Guid?>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = new Guid("d6f01585-5d6a-44ff-aaad-2d8648268582"),
                            Address = "Orani, Bataan",
                            Birthdate = new DateTime(2020, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactNumber = "09485209870",
                            Email = "JohnJohn@Doemail.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "$2b$10$3JybgWnMBTzgO7HJEi6ulOctwgL9E8oIyvmkf65iKm9nabeHo0P.O",
                            Sex = "Male",
                            UserRole = 0
                        },
                        new
                        {
                            UserID = new Guid("aca4e15f-379b-44ce-90c0-ce8374cd0cd7"),
                            Address = "Dinalupihan, Bataan",
                            Birthdate = new DateTime(1010, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactNumber = "09485209870",
                            Email = "JaneJane@Doemail.com",
                            FirstName = "Jane",
                            LastName = "Doe",
                            Password = "$2b$10$3JybgWnMBTzgO7HJEi6ulOctwgL9E8oIyvmkf65iKm9nabeHo0P.O",
                            Sex = "Female",
                            UserRole = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
